export const recipes = [
  // {
  //   title: "Very Romantic Pancakes Made by Alex",
  //   ingredients: [
  //     "1/2 cup waffle mix",
  //     "1/2 cup water",
  //     "1  teaspoon creatine",
  //     "1 egg",
  //   ],
  //   serving_size: "2 waffles",
  //   steps: [
  //     "Mix everything",
  //     "Put in the waffle maker",
  //     "Yup!",
  //     "Serve with fruits",
  //   ],
  // },
  {
    title: "Strawberry Daifuku",
    ingredients: [
      "6 strawberries",
      "150 g red bean paste",
      "potato starch/cornstarch (for dusting)",
      "100 g sweet rice flour/glutinous rice flour",
      "20 g sugar",
      "150 ml water",
    ],
    serving_size: "6 mochis",
    steps: [
      "Rinse, dry, and hull the strawberries.",
      "Divide red bean paste into 6 same size balls. red bean paste gets sticky on your hands, so wash your hands and dry completely each time you make a ball.",
      "Wrap the strawberries with red bean paste. Leave the tip of the strawberry uncovered. Wash your hands and dry completely each time you wrap a strawberry with red bean paste.",
      "In a medium microwave-safe glass bowl, mix shiratamako and sugar with a whisk.",
      "Using a silicone spatula, slowly add water in 3 parts and stir until the mixture has reached a thick consistency. Cover loosely with plastic wrap.",
      "First, microwave 1 minute (for 1100W microwave). Mix well with a wet silicone spatula. The mixture is still whitish and floury.",
      "For the second time, microwave 1 minute again, and mix well with the wet silicone spatula. Now it starts to resemble mochi, but there are still some floury parts.",
      "For the last time, microwave only 30 seconds. Now the mochi mixture should look translucent.",
      "Sift corn starch on the tray and put the mochi on top.",
      "With silicone spatula or kitchen scraper, fold the mochi in half one time so it won’t be as sticky and then divide into 6 equal pieces.",
      "Put some corn starch on your hands and flatten and expand each mochi into a 3” (7.6 cm) round or square. Then put the red bean paste covered strawberry on top of it, with the tip facing down.",
      "Start covering the strawberry from all sides and use your thumb to hold the mochi on top.",
      "When all sides of mochi meet at the top, twist and close. Hold the mochi with both hands and form into nice round shape. Repeat the process for the remaining mochi.",
      "Serve at room temperature.",
    ],
  },
  {
    title: "Healthy Banana Bread",
    ingredients: [
      "2 very ripe bananas, mashed",
      "2 eggs",
      "1 1/4 cup yogurt",
      "1/2 teaspoon pure vanilla extract",
      "1 1/2 cups all-purpose flour",
      "1/2 cup whole-wheat flour",
      "3/4 teaspoon salt",
      "1/4 teaspoon baking powder",
      "1/2 teaspoon baking soda",
      "2/3 cup chopped walnuts"
    ],
    serving_size: "1 2lb loaf",
    steps: [
      "Put everything in bread machine in this order",
      "Bake on cake mode",
      "When the add-in timer beeps, add the walnuts.",
    ],
  },


  {
    title: "Basque Cheesecake by Bon Appetit",
    ingredients: [
      "2 lb. cream cheese, room temperature",
      "1½ cups sugar",
      "6 large eggs",
      "2 cups heavy cream",
      "1 tsp. kosher salt",
      "1 tsp. vanilla extract",
      "⅓ cup all-purpose flour",
    ],
    serving_size: "1 10 inch cake",
    steps: [
"Place a rack in middle of oven; preheat to 400°.",
"Butter pan, then line with 2 overlapping 16x12 inch sheets of parchment, making sure parchment comes at least 2 inches above top of pan on all sides. Because the parchment needs to be pleated and creased in some areas to fit in pan, you won’t end up with a clean, smooth outer edge to the cake; that’s okay! Place pan on a rimmed baking sheet.",
"Beat cream cheese and sugar in the bowl of a stand mixer fitted with the paddle attachment on medium-low speed, scraping down sides of bowl, until very smooth, no lumps remain, and sugar has dissolved, about 2 minutes.",
"Increase speed to medium and add eggs one at a time, beating each egg 15 seconds before adding the next. Scrape down sides of bowl, then reduce mixer speed to medium-low.",
"Add cream, salt, and vanilla and beat until combined, about 30 seconds.",
"Turn off mixer and sift flour evenly over cream cheese mixture.",
"Beat on low speed until incorporated, about 15 seconds. Scrape down sides of bowl (yet again) and continue to beat until batter is very smooth, homogenous, and silky, about 10 seconds.",
"Pour batter into prepared pan. Bake cheesecake until deeply golden brown on top and still very jiggly in the center, 60–65 minutes.",
"Let cool slightly (it will fall drastically as it cools), then unmold. Let cool completely. Carefully peel away parchment from sides of cheesecake. Slice into wedges and serve at room temperature, preferably with a glass of sherry alongside."
    ],
  },
  {
    title: "Microwave Mochi",
    ingredients: [
      `50g Glutinous rice flour`,
      `90g Water`,
      `10g Sugar`,
      `cornstarch`,
    ],
    serving_size: "many mochis",
    steps: [
      "In a non-metal bowl mix the glutinous rice flour, water, and sugar until there are no lumps.",
      "Put the bowl in the microwave and heat it on high heat (1100w) for 1 minute. Take it out and stir with wet rubber spatula.",
      "Cover again and cook for 1 minute. Stir again.",
      "Cover and cook for 30 seconds to finish cooking. The color of mochi should change from white to almost translucent.",
      "Cover the work surface with parchment paper and dust it generously with corn starch.",
      "Then transfer the cooked mochi on top.",
      "To prevent from sticking, sprinkle more potato starch on top of the mochi. Once it’s cool down a bit, you can spread the mochi into a thin layer with your hands or with a rolling pin. Make sure to apply potato starch on your hands and the rolling pin. I recommend using a rolling pin because it’s easier to evenly spread out.",
      "Cut out into small pieces and fill with mango filling"
    ],
  },
  {
    title: "Poached Pear Earl Gray Loaf",
    ingredients: [
      `4 cups water`,
      `5 Earl Grey tea bags, or 5 tsp loose leaf Earl grey tea`,
      `1 cup sugar`,
      `3 medium peeled pears`,
      `1-⅓ cup (200 g) all-purpose flour`,
      `½ cup (50 g) cocoa powder`,
      `1 teaspoon baking soda`,
      `½ teaspoon salt`,
      `⅔ cup (165 ml) milk`,
      `⅓ cup (75 g) yogurt`,
      `½ cup (113 g) room temperature butter`,
      `1 cup (200 g) brownsugar`,
      `2 large eggs`,
    ],
    serving_size: "1 loaf",
    steps: [
      "First, poach the pears. Bring the water to a boil on the stovetop in a medium-sized pot. Add the Earl Grey tea bags or leaves and turn down the heat. Let the tea steep in the boiling water for 5 minutes to infuse. Remove the tea bags, add the sugar to the pot, and stir to dissolve.",
      "Add the peeled pears to the pot. Turn up the heat to medium-high and bring the tea back to a boil. Once boiling, reduce the heat to medium-low and let the pears simmer for 20 to 25 minutes until tender. Once the pears are tender, carefully remove them from the pot and set them aside on a plate or in a bowl to cool.",
      "Preheat the oven to 350°F (180ºC). Grease a loaf tin lightly with butter. Line the pan with a parchment paper sling with overhang on both sides.",
      "In a large bowl, whisk together the flour, cocoa, baking soda, and salt.",
      "Mix the milk and yogurt in another bowl until smooth.",
      "Using a hand or stand mixer beat the butter until light and fluffy, about 5 to 7 minutes. Add the brown sugar and continue to mix a few minutes more.",
      "Add the eggs, one at a time, and mix until well incorporated.",
      "Add in half of the flour mixture and half of the milk mixture. Mix everything together on low speed until well incorporated. Add in the remaining flour and milk mixtures and continue to mix on low speed until the chocolate batter is just combined.",
      "Add a few spoonfuls of batter to the bottom of the prepared loaf tin. Place the poached pears, bottom side down in the batter. Spoon the remaining chocolate batter around the three pears. Bake the loaf for 50 to 55 minutes, or until the top springs gently back when touched, then transfer it to a wire cooling rack. Let the loaf cool for 20 minutes, then remove it from the tin. Cool the loaf completely before slicing."
    ],
  },
];